syntax = "proto3";

package dynamo;

option go_package = "pkg/gen";

//--------------------------------------------------------------

// The server struct must implement This service and its its Methods
service NodeDiscoveryService { // calling to seeder node
  rpc RegisterNode(Node) returns (NodeList);
}

message Node {
  uint32          server_id     = 1;
  repeated uint64 server_hashes = 2;
}

message NodeList {
  repeated Node nodes = 1;
}


// --------------------REPLICATION-----------------------

service ReplicationService { // 
  rpc TransferWrite(PutMessage) returns (Ack);
  rpc GetReadResponse(GetMessage) returns (ReadAck);
  rpc TransferHandoffWrite(HandOffData) returns (Ack);
}

message Ack{
  bool   success   = 1;
  string message   = 2; // optional message string
  int64  server_id = 3; // serverId sending the ACK
}

message HandOffData {
  int64      server_id = 1;
  PutMessage kv        = 2;
}

message PutMessage {
  int64 key   = 1;
  int64 value = 2;
}

message GetMessage {
  int64 key = 1;
}

message ReadAck {
  int64 value = 1;
}

// -------------------------GOSSIP---------------------------

service GossipService {
  rpc Gossip(GossipMessage) returns (Ack);
}

message GossipMessage{
  map<int64,ServerStateMessage> server_state = 1;
}

message ServerStateMessage {
  int64 server_id = 1;
  HeartBeatMessage heartbeat = 2;
  int64 server_state = 3;
}


message HeartBeatMessage{
  int64 heartbeat_number = 1;
  string timestamp = 2; // actual go stores the time in time.Time

}












